function matlab_ollama_dock()
%MATLAB_OLLAMA_DOCK Prototype dock-style local Ollama helper.
%   Keyboard:
%   - Ctrl+Enter: send
%   - Enter in prompt: newline
%   - Escape: hide

fig = figure( ...
    'Name', 'Utility', ...
    'NumberTitle', 'off', ...
    'MenuBar', 'none', ...
    'ToolBar', 'none', ...
    'DockControls', 'on', ...
    'WindowStyle', 'docked', ...
    'Color', [0.97 0.97 0.98], ...
    'WindowKeyPressFcn', @handleFigureKeyPress);

panel = uipanel( ...
    'Parent', fig, ...
    'Units', 'normalized', ...
    'Position', [0 0 1 1], ...
    'BorderType', 'none', ...
    'BackgroundColor', [0.97 0.97 0.98]);

promptEdit = uicontrol( ...
    'Parent', panel, ...
    'Style', 'edit', ...
    'Units', 'normalized', ...
    'Position', [0.03 0.72 0.94 0.25], ...
    'Max', 2, ...
    'Min', 0, ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Consolas', ...
    'FontSize', 10, ...
    'String', '');

hintText = uicontrol( ...
    'Parent', panel, ...
    'Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.03 0.67 0.94 0.035], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.97 0.97 0.98], ...
    'ForegroundColor', [0.45 0.47 0.50], ...
    'FontSize', 8, ...
    'String', 'Ctrl+Enter = Send | Enter = newline | Esc = hide');

sendButton = uicontrol( ...
    'Parent', panel, ...
    'Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'Position', [0.03 0.58 0.46 0.08], ...
    'String', 'Send', ...
    'Callback', @sendPrompt);

hideButton = uicontrol( ...
    'Parent', panel, ...
    'Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'Position', [0.51 0.58 0.46 0.08], ...
    'String', 'Hide', ...
    'Callback', @(~, ~) set(fig, 'Visible', 'off'));

outputEdit = uicontrol( ...
    'Parent', panel, ...
    'Style', 'edit', ...
    'Units', 'normalized', ...
    'Position', [0.03 0.10 0.94 0.45], ...
    'Max', 2, ...
    'Min', 0, ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Consolas', ...
    'FontSize', 10, ...
    'Enable', 'on', ...
    'String', '');

statusText = uicontrol( ...
    'Parent', panel, ...
    'Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.03 0.02 0.94 0.06], ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', [0.97 0.97 0.98], ...
    'ForegroundColor', [0.35 0.38 0.42], ...
    'FontSize', 9, ...
    'String', 'Ready');

setappdata(0, 'llm_dock_figure', fig);

    function handleFigureKeyPress(~, event)
        modifiers = string(event.Modifier);

        if strcmp(event.Key, 'escape')
            set(fig, 'Visible', 'off');
            return;
        end

        if any(modifiers == "control") && (strcmp(event.Key, 'return') || strcmp(event.Key, 'enter'))
            sendPrompt();
        end
    end

    function sendPrompt(~, ~)
        rawPrompt = string(get(promptEdit, 'String'));
        promptText = strtrim(join(rawPrompt, newline));

        if strlength(promptText) == 0
            set(statusText, 'String', 'Empty prompt');
            return;
        end

        set(sendButton, 'Enable', 'off');
        set(statusText, 'String', 'Running...');
        set(outputEdit, 'String', '');
        drawnow;

        try
            responseText = llm(promptText);
            set(outputEdit, 'String', cellstr(splitlines(responseText)));
            set(promptEdit, 'String', '');
            set(statusText, 'String', 'Done');
        catch err
            set(outputEdit, 'String', err.message);
            set(statusText, 'String', 'Error');
        end

        set(sendButton, 'Enable', 'on');
        uicontrol(promptEdit);
    end
end
